<a href="https://colab.research.google.com/github/n-pimruda/Java_OOP/blob/main/66160322_G2_w3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**การนับแถวเริ่มนับแถวที่ 0, 1, 2,...**
**การนับคอลัมน์เริ่มนับคอลัมน์ที่ 0, 1, 2,...**

**ให้นิสิต เลือกเมนู File-->Save a copy in drive เพื่อคัดลอกไฟล์ไปไว้ในไดร์ฟของนิสิตก่อน และเปลี่ยนชื่อไฟล์เป็น รหัสนิสิต_week3.ipynb ก่อนส่งงานค่ะ**

1. จงสร้างเมทริกซ์     
A =
\begin{bmatrix}
2 & -2 & 0   \\
1 & 4 & -5   \\
0 & 2 & 3   \\
\end{bmatrix}

โดยใช้ Python

1.1 จงตรวจสอบว่าเมทริกซ์ A เป็นเมทริกซ์เอกฐาน หรือไม่ ถ้าเป็นแสดงข้อความ Singular matrix.

1.2 จงแปลงเมทริกซ์ A ให้เป็นเมทริกซ์เอ๊กซลอน (Echelon form matrix) โดยการดำเนินการตามแนวแถว (Elementary row oparation)



1.3 จงหาเมทริกซ์ผกผัน (Inverse matrix) ของเมทริกซ์ A

1.4 จงตรวจสอบเมทริกซ์ผลลัพธ์ที่ได้จากข้อ 1.3 ว่าถูกต้องหรือไม่ หากถูกต้องแสดงข้อความว่า Correct หากไม่ถูกต้องแสดงข้อความ Incorrect โดยหากไม่ถูกต้องจงแก้ไขให้ถูกต้องด้วย

2.จงสร้างเมทริกซ์     
A =
\begin{bmatrix}
1 & 2 & 1  \\
2 & -4 & 5  \\
2 & 4 & 2
\end{bmatrix}
โดยใช้ Python

2.1	จงหา det(A)

2.2 จงหา Rank ของเมทริกซ์ที่กำหนดโดยใช้วิธีหาเมทริกซ์เอ็ซลอนลดรูปแบบแถว


In [ ]:
#ชื่อ พิมฤดา ชุมสุข รหัส 66160322

In [ ]:
#1. จงสร้างเมทริกซ์ A = [[2,-2,0], [1,4,-5], [0,2,3]]
import numpy as np
A = np.array([[2,-2,0], [1,4,-5], [0,2,3]])
print("Matrix A = ")
print(A)

Matrix A = 
[[ 2 -2  0]
 [ 1  4 -5]
 [ 0  2  3]]


In [ ]:
#1.1 จงตรวจสอบว่าเมทริกซ์ A เป็นเมทริกซ์เอกฐาน หรือไม่ ถ้าเป็นแสดงข้อความ Singular matrix.
print("1.1")
detA = np.around(np.linalg.det(A),decimals=2)
print("detA = ", detA)
if np.linalg.det(A) == 0 :
  print("Singular matrix.")
else :
  print("Not Singular matrix")

1.1
detA =  50.0
Not Singular matrix)


In [ ]:
 #1.2 จงแปลงเมทริกซ์ A ให้เป็นเมทริกซ์เอ๊กซลอน (Echelon form matrix)
 #โดยการดำเนินการตามแนวแถว (Elementary row oparation)
print("1.2")
print('Matrix A:')
print(A)
n=A.shape[0]
AI = np.hstack([A,np.identity(n)])
print('Matrix [A:I]:')
print(AI)

def switch_rows(A,i,j):
  A[[i, j]] = A[[j, i]]
  return A

def scale_row(A,k,i):
  A[i] = k * A[i]
  return A

def add_row(A,k,i,j):
  A[i] += k * A[j]
  return A

# สลับแถว R1<->R2
A1 = switch_rows(AI,0,1)
print('#1 Matrix [A:I]:')
print(A1)
#เปลี่ยน a12 ให้เป็น 0 โดย R2 -> R2-2R1
A2 = add_row(A1,-2,1,0)
print('#2 Matrix [A:I]:')
print(A2)
#เปลี่ยน a22 ให้เป็น 1 โดย R2 -> -1/10R2
A3 = scale_row(A2,-1/10,1)
print('#3 Matrix [A:I]:')
print(A3)
#a12, a32 ให้เป็น 0 โดย R1-> R1-4R2 / R3-> R3-2R2
A4 = add_row(A3,-4,0,1)
A4 = add_row(A3,-2,2,1)
print('#4 Matrix [A:I]:')
print(A4)
#เปลี่ยน a33 = 0 โดย R3 -> 1/5R3
A5 = scale_row(A4,1/5,2)
print('#5 Matrix [A:I]:')
print(A5)
#เปลี่ยนให้ a13, a23 เป็น 0 โดย R1 -> R1+R3 / R2 -> R2+R3
A6 = add_row(A5,1,0,2)
A6 = add_row(A5,1,1,2)
print('#6 Matrix [A:I]:')
print(A6)

1.2
Matrix A:
[[ 2 -2  0]
 [ 1  4 -5]
 [ 0  2  3]]
Matrix [A:I]:
[[ 2. -2.  0.  1.  0.  0.]
 [ 1.  4. -5.  0.  1.  0.]
 [ 0.  2.  3.  0.  0.  1.]]
#1 Matrix [A:I]:
[[ 1.  4. -5.  0.  1.  0.]
 [ 2. -2.  0.  1.  0.  0.]
 [ 0.  2.  3.  0.  0.  1.]]
#2 Matrix [A:I]:
[[  1.   4.  -5.   0.   1.   0.]
 [  0. -10.  10.   1.  -2.   0.]
 [  0.   2.   3.   0.   0.   1.]]
#3 Matrix [A:I]:
[[ 1.   4.  -5.   0.   1.   0. ]
 [-0.   1.  -1.  -0.1  0.2 -0. ]
 [ 0.   2.   3.   0.   0.   1. ]]
#4 Matrix [A:I]:
[[ 1.   0.  -1.   0.4  0.2  0. ]
 [-0.   1.  -1.  -0.1  0.2 -0. ]
 [ 0.   0.   5.   0.2 -0.4  1. ]]
#5 Matrix [A:I]:
[[ 1.    0.   -1.    0.4   0.2   0.  ]
 [-0.    1.   -1.   -0.1   0.2  -0.  ]
 [ 0.    0.    1.    0.04 -0.08  0.2 ]]
#6 Matrix [A:I]:
[[ 1.    0.    0.    0.44  0.12  0.2 ]
 [ 0.    1.    0.   -0.06  0.12  0.2 ]
 [ 0.    0.    1.    0.04 -0.08  0.2 ]]


In [ ]:
#1.3 จงหาเมทริกซ์ผกผัน (Inverse matrix) ของเมทริกซ์ A
print("Inverse of Matrix A = ")
print(np.around(np.linalg.inv(A),decimals=2))

Inverse of Matrix A = 
[[ 0.44  0.12  0.2 ]
 [-0.06  0.12  0.2 ]
 [ 0.04 -0.08  0.2 ]]


In [ ]:
#
Ainv = A6[:,n:]
print('Matrix A inverse:')
print(Ainv)

Matrix A inverse:
[[ 0.44  0.12  0.2 ]
 [-0.06  0.12  0.2 ]
 [ 0.04 -0.08  0.2 ]]


In [ ]:
#1.4 จงตรวจสอบเมทริกซ์ผลลัพธ์ที่ได้จากข้อ 1.3 ว่าถูกต้องหรือไม่
#หากถูกต้องแสดงข้อความว่า Correct หากไม่ถูกต้องแสดงข้อความ Incorrect โดยหากไม่ถูกต้องจงแก้ไขให้ถูกต้องด้วย
print("1.4")
print('Matrix A @ Matrix A inverse')
print(A@Ainv)
print(np.around(A@Ainv,decimals=0))
if np.array_equal(np.around(A@Ainv,decimals=0),np.identity(n)):
  print("Correct")
else:
  print("Incorrect")

1.4
Matrix A @ Matrix A inverse
[[ 1.00000000e+00 -1.11022302e-16  0.00000000e+00]
 [ 2.77555756e-17  1.00000000e+00 -5.55111512e-17]
 [ 2.77555756e-17 -5.55111512e-17  1.00000000e+00]]
[[ 1. -0.  0.]
 [ 0.  1. -0.]
 [ 0. -0.  1.]]
Correct


In [ ]:
#2. จงสร้างเมทริกซ์ A = [[1,2,1], [2,-4,5], [2,4,2]]
A = np.array([[1,2,1], [2,-4,5], [2,4,2]])
print("Matrix A = ")
print(A)

Matrix A = 
[[ 1  2  1]
 [ 2 -4  5]
 [ 2  4  2]]


In [ ]:
#2.1 จงหา det(A)
print("2.1")
detA = np.around(np.linalg.det(A),decimals=2)
print("detA = ", detA)

2.1
detA =  0.0


In [ ]:
#2.2 จงหา Rank ของเมทริกซ์ที่กำหนดโดยใช้วิธีหาเมทริกซ์เอ็ซลอนลดรูปแบบแถว
A = np.array([[1,2,1], [2,-4,5], [2,4,2]])
print('Matrix A:')
print(A)
n=A.shape[0]

def switch_rows(A,i,j):
  A[[i, j]] = A[[j, i]]
  return A

def scale_row(A,k,i):
  A[i] = k * A[i]
  return A

def add_row(A,k,i,j):
  A[i] += k * A[j]
  return A

#เปลี่ยน a21, a31 เป็น 0 โดย R->R2-2R1 / R3->R3-2R1
A1 = add_row(A,-2,1,0)
A1 = add_row(A,-2,2,0)
print('#1 Matrix A:')
print(A1)
#เปลี่ยน a22 เป็น 1 โดย R2->-1/8R2
A2 = scale_row(A1,-1/8,1)
print('#2 Matrix A:')
print(A2)
#เปลี่ยน a12 เป็น 0 โดย R1-> R1-2R2
A3 = add_row(A2,-2,0,1)
print('#3 Matrix A:')
print(A3)

Matrix A:
[[ 1  2  1]
 [ 2 -4  5]
 [ 2  4  2]]
#1 Matrix A:
[[ 1  2  1]
 [ 0 -8  3]
 [ 0  0  0]]
#2 Matrix A:
[[1 2 1]
 [0 1 0]
 [0 0 0]]
#3 Matrix A:
[[1 0 1]
 [0 1 0]
 [0 0 0]]


In [ ]:
print("2.2")
print(' Echelon Matrix A:')
print(A3)
result = np.all((A3 == 0), axis=1)
print('Is zero row?',result)
zero_row=len([i for i in range(n) if result[i] ])
rankA=n-zero_row
print('2.2 Rank A =',rankA)
print('2.2 Rank A = ',np.linalg.matrix_rank(A))

2.2
 Echelon Matrix A:
[[1 0 1]
 [0 1 0]
 [0 0 0]]
Is zero row? [False False  True]
2.2 Rank A = 2
2.2 Rank A =  2
